language: node_js

node_js:
  - 4.2

script:
  - docker build -f Docker/Dockerfile -t property-locator-node .

after_success:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  - docker tag property-locator-node $DOCKER_USER/property-locator-node:latest
  - docker push $DOCKER_USER/property-locator-node:latest
