version: "2.1"

services:
  scrape_server:
    container_name: scraper-node
    image: property-scraper:latest
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - /usr/src/app
    networks:
      - scraper_net

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: sraper-postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "4420:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10

volumes:
  pgadmin-data:

networks:
  scraper_net:
    external: true
